#!/usr/bin/env node
/**
 * Sinh file locale bổ sung từ locale-delta.
 *
 * Đọc scripts/i18n/locale-delta-<name>.json (flat keys: "system.user.nickname": "用户昵称")
 * -> tạo object lồng nhau, ghi ra src/locales/generated/<name>.<lang>.ts cho zh-CN / en / vi.
 *   - zh-CN: value = chuỗi Trung gốc.
 *   - en / vi: value = '' (skeleton, dịch sau) — nếu key đã tồn tại thì giữ nguyên.
 *
 * KHÔNG đụng vào key REUSE (common.*, action.*) vì chúng đã có sẵn trong locale chính.
 *
 * Usage: node scripts/i18n/gen-locale.mjs user
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = fileURLToPath(new URL('.', import.meta.url))
const ROOT = join(__dirname, '..', '..')

const name = process.argv[2]
if (!name) {
  console.error('Usage: node scripts/i18n/gen-locale.mjs <name>')
  process.exit(1)
}

const deltaPath = join(__dirname, `locale-delta-${name}.json`)
const delta = JSON.parse(readFileSync(deltaPath, 'utf8'))

// build nested object từ flat keys
function nest(flat, transform) {
  const root = {}
  for (const [k, zh] of Object.entries(flat)) {
    const parts = k.split('.')
    let cur = root
    for (let i = 0; i < parts.length - 1; i++) {
      cur[parts[i]] = cur[parts[i]] || {}
      cur = cur[parts[i]]
    }
    cur[parts[parts.length - 1]] = transform(zh)
  }
  return root
}

function serialize(obj, indent = 2) {
  const pad = ' '.repeat(indent)
  const entries = Object.entries(obj).map(([k, v]) => {
    const key = /^[a-zA-Z_$][\w$]*$/.test(k) ? k : `'${k}'`
    if (v && typeof v === 'object') {
      return `${pad}${key}: ${serialize(v, indent + 2)}`
    }
    // Escape cú pháp vue-i18n message: '{' và '}' là literal placeholder -> bọc thành {'{'} {'}'}.
    const escaped = String(v).replace(/\{/g, "{'{'}").replace(/\}/g, "{'}'}").replace(/'/g, "\\'")
    return `${pad}${key}: '${escaped}'`
  })
  return `{\n${entries.join(',\n')}\n${' '.repeat(indent - 2)}}`
}

const outDir = join(ROOT, 'src', 'locales', 'generated')
if (!existsSync(outDir)) mkdirSync(outDir, { recursive: true })

// en/vi tạm để giá trị tiếng Trung (UI vẫn đọc được trong khi chờ dịch).
// Sau khi dịch xong thì thay giá trị. Có thể dò các dòng còn ký tự Trung để biết chỗ chưa dịch.
const langs = {
  'zh-CN': (zh) => zh,
  en: (zh) => zh,
  vi: (zh) => zh
}

for (const [lang, transform] of Object.entries(langs)) {
  const nested = nest(delta, transform)
  const body = serialize(nested)
  const content = `// AUTO-GENERATED by scripts/i18n/gen-locale.mjs — bổ sung i18n cho "${name}".\n// ${lang === 'zh-CN' ? 'Bản gốc tiếng Trung.' : 'Cần dịch các chuỗi rỗng.'}\nexport default ${body}\n`
  const outPath = join(outDir, `${name}.${lang}.ts`)
  writeFileSync(outPath, content, 'utf8')
  console.log('  ✎', outPath.replace(ROOT + '/', ''))
}

console.log('Done. Keys:', Object.keys(delta).length)
console.log('\nBước tiếp: import generated vào src/locales/<lang>.ts và deep-merge.')
