/**
 * This is a sample file that should be replaced with the actual translation.
 *
 * Checkout https://github.com/bpmn-io/bpmn-js-i18n for a list of available
 * translations and labels to translate.
 */
export default {
  // 添加部Minute
  'Append EndEvent': 'Append End Event',
  'Append Gateway': 'Append Gateway',
  'Append Task': 'Append Task',
  'Append Intermediate/Boundary Event': 'Append Intermediate/Boundary Event',
  TextAnnotation: '文本注释',
  'Activate the global connect tool': 'Activate the global connect tool',
  'Append {type}': 'Add {type}',
  'Add Lane above': '在上面添加道',
  'Divide into two Lanes': 'Minute割成两个道',
  'Divide into three Lanes': 'Minute割成三个道',
  'Add Lane below': '在下面添加道',
  'Append compensation activity': 'Append Compensation Activity',
  'Change type': '修改Type',
  'Connect using Association': '使用关联连接',
  'Connect using Sequence/MessageFlow or Association': '使用顺序/Message流或者关联连接',
  'Connect using DataInputAssociation': '使用数据输入关联连接',
  Remove: 'Remove',
  'Activate the hand tool': 'Activate the hand tool',
  'Activate the lasso tool': 'Activate the lasso tool',
  'Activate the create/remove space tool': 'Activate the create/remove space tool',
  'Create expanded SubProcess': '创建扩展子过程',
  'Create IntermediateThrowEvent/BoundaryEvent': '创建中间抛出Event/边界Event',
  'Create Pool/Participant': '创建池/参与者',
  'Participant Multiplicity': '参与者多重性',
  'Empty pool/participant (removes content)': 'Clear Pool/Participant (remove content)',
  'Empty pool/participant': '收缩池/参与者',
  'Expanded pool/participant': '展开池/参与者',
  'Parallel Multi-Instance': 'Parallel Multiple Event',
  'Sequential Multi-Instance': 'Sequential Multiple Event',
  DataObjectReference: '数据对象参考',
  DataStoreReference: '数据存储参考',
  'Data object reference': '数据对象引用 ',
  'Data store reference': '数据存储引用 ',
  Loop: 'Loop',
  'Ad-hoc': '即席',
  'Create {type}': '创建 {type}',
  Task: '任务',
  'Send Task': '发送任务',
  'Receive Task': '接收任务',
  'User Task': 'User Task',
  'Manual Task': '手工任务',
  'Business Rule Task': '业务规则任务',
  'Service Task': '服务任务',
  'Script Task': 'Script Task',
  'Call Activity': 'Call Activity',
  'Sub-Process (collapsed)': '子流程（折叠的）',
  'Sub-Process (expanded)': '子流程（展开的）',
  'Ad-hoc sub-process': '即席子流程',
  'Ad-hoc sub-process (collapsed)': '即席子流程（折叠的）',
  'Ad-hoc sub-process (expanded)': '即席子流程（展开的）',
  'Start Event': '开始Event',
  StartEvent: '开始Event',
  'Intermediate Throw Event': '中间Event',
  'End Event': 'End Event',
  EndEvent: 'End Event',
  'Create StartEvent': '创建开始Event',
  'Create EndEvent': '创建End Event',
  'Create Task': '创建任务',
  'Create User Task': '创建User Task',
  'Create Call Activity': '创建Call Activity',
  'Create Service Task': '创建服务任务',
  'Create Gateway': '创建网关',
  'Create DataObjectReference': '创建数据对象',
  'Create DataStoreReference': '创建数据存储',
  'Create Group': '创建Minute组',
  'Create Intermediate/Boundary Event': '创建中间/边界Event',
  'Message Start Event': 'Message Start Event',
  'Timer Start Event': '定Hour开始Event',
  'Conditional Start Event': 'Conditional Start Event',
  'Signal Start Event': '信号开始Event',
  'Error Start Event': 'Error Start Event',
  'Escalation Start Event': '升级开始Event',
  'Compensation Start Event': 'Compensation Start Event',
  'Message Start Event (non-interrupting)': 'Message Start Event (Non-interrupting)',
  'Timer Start Event (non-interrupting)': '定Hour开始Event（非中断）',
  'Conditional Start Event (non-interrupting)': 'Conditional Start Event (Non-interrupting)',
  'Signal Start Event (non-interrupting)': '信号开始Event（非中断）',
  'Escalation Start Event (non-interrupting)': '升级开始Event（非中断）',
  'Message Intermediate Catch Event': 'Message Intermediate Catch Event',
  'Message Intermediate Throw Event': 'Message Intermediate Throw Event',
  'Timer Intermediate Catch Event': '定Hour中间捕获Event',
  'Escalation Intermediate Throw Event': '升级中间抛出Event',
  'Conditional Intermediate Catch Event': '条件中间捕获Event',
  'Link Intermediate Catch Event': 'Link Intermediate Catch Event',
  'Link Intermediate Throw Event': 'Link Intermediate Throw Event',
  'Compensation Intermediate Throw Event': 'Compensation Intermediate Throw Event',
  'Signal Intermediate Catch Event': '信号中间捕获Event',
  'Signal Intermediate Throw Event': '信号中间抛出Event',
  'Message End Event': 'Message End Event',
  'Escalation End Event': '定HourEnd Event',
  'Error End Event': 'Error End Event',
  'Cancel End Event': 'CancelEnd Event',
  'Compensation End Event': 'Compensation End Event',
  'Signal End Event': '信号End Event',
  'Terminate End Event': 'Terminate End Event',
  'Message Boundary Event': 'Message Boundary Event',
  'Message Boundary Event (non-interrupting)': 'Message Boundary Event (Non-interrupting)',
  'Timer Boundary Event': '定Hour边界Event',
  'Timer Boundary Event (non-interrupting)': '定Hour边界Event（非中断）',
  'Escalation Boundary Event': '升级边界Event',
  'Escalation Boundary Event (non-interrupting)': '升级边界Event（非中断）',
  'Conditional Boundary Event': 'Conditional Boundary Event',
  'Conditional Boundary Event (non-interrupting)': 'Conditional Boundary Event (Non-interrupting)',
  'Error Boundary Event': 'Error Boundary Event',
  'Cancel Boundary Event': 'Cancel边界Event',
  'Signal Boundary Event': '信号边界Event',
  'Signal Boundary Event (non-interrupting)': '信号边界Event（非中断）',
  'Compensation Boundary Event': 'Compensation Boundary Event',
  'Exclusive Gateway': '互斥网关',
  'Parallel Gateway': '并行网关',
  'Inclusive Gateway': 'Inclusive Gateway',
  'Complex Gateway': '复杂网关',
  'Event-based Gateway': 'Event网关',
  Transaction: 'Transfer',
  'sub-process': '子流程',
  'Event sub-process': 'Event子流程',
  'Collapsed Pool': '折叠池',
  'Expanded Pool': '展开池',

  // Errors
  'no parent for {element} in {parent}': '在{parent}里，{element}没有父类',
  'no shape type specified': 'No shape type specified',
  'flow elements must be children of pools/participants': 'Flow element must be a child of a Pool/Participant',
  'out of bounds release': 'out of bounds release',
  'more than {count} child lanes': '子道大于{count} ',
  'element required': '元素不能为空',
  'diagram not part of bpmn:Definitions': 'The diagram does not comply with the BPMN spec',
  'no diagram to display': 'No process diagram to display',
  'no process or collaboration to display': 'No process/collaboration to display',
  'element {element} referenced by {referenced}#{property} not yet drawn':
    'Element {element} referenced by {referenced}#{property} is not yet drawn',
  'already rendered {element}': '{element} 已被渲染',
  'failed to import {element}': '导入{element}失败',
  //属性面板的参数
  Id: 'ID',
  Name: 'Name',
  General: 'General',
  Details: 'Detail',
  'Message Name': 'Message Name',
  Message: 'Message',
  Initiator: '创建者',
  'Asynchronous Continuations': '持续异步',
  'Asynchronous Before': 'Async Before',
  'Asynchronous After': 'Async After',
  'Job Configuration': '工作Config',
  Exclusive: 'Exclude',
  'Job Priority': '工作优先级',
  'Retry Time Cycle': 'Retry Time Cycle',
  Documentation: '文档',
  'Element Documentation': '元素文档',
  'History Configuration': '历史Config',
  'History Time To Live': '历史的生存Hour间',
  Forms: 'Form',
  'Form Key': 'Form Key',
  'Form Fields': 'Form Field',
  'Business Key': '业务key',
  'Form Field': 'Form Field',
  ID: 'ID',
  Type: 'Type',
  Label: 'Name',
  'Default Value': 'Default Value',
  'Default Flow': 'Default Flow',
  'Conditional Flow': 'Conditional Flow',
  'Sequence Flow': 'Normal Flow',
  Validation: 'Validate',
  'Add Constraint': 'Add Constraint',
  Config: 'Config',
  Properties: '属性',
  'Add Property': 'Add Property',
  Value: 'Value',
  Listeners: 'Listener',
  'Execution Listener': '执行监听',
  'Event Type': 'Event Type',
  'Listener Type': 'Listener Type',
  'Java Class': 'Java Class',
  Expression: 'Expression',
  'Must provide a value': '必须提供一个Value',
  'Delegate Expression': 'Delegate Expression',
  Script: 'Script',
  'Script Format': 'Script Format',
  'Script Type': 'Script Type',
  'Inline Script': 'Inline Script',
  'External Script': 'External Script',
  Resource: 'Resource',
  'Field Injection': '字段注入',
  Extensions: '扩展',
  'Input/Output': 'Input/Output',
  'Input Parameters': 'Input Parameter',
  'Output Parameters': 'Output Parameter',
  Parameters: '参数',
  'Output Parameter': 'Output Parameter',
  'Timer Definition Type': 'Timer定义Type',
  'Timer Definition': 'Timer定义',
  Date: 'Date',
  Duration: '持续',
  Cycle: 'Loop',
  Signal: '信号',
  'Signal Name': 'Signal Name',
  Escalation: '升级',
  Error: 'Error',
  'Link Name': 'Link Name',
  Condition: 'Condition Name',
  'Variable Name': '变量Name',
  'Variable Event': '变量Event',
  'Specify more than one variable change event as a comma separated list.':
    '多个变量Event以逗号隔开',
  'Wait for Completion': 'Wait for Completion',
  'Activity Ref': 'Activity Reference',
  'Version Tag': 'Version Tag',
  Executable: '可执行文件',
  'External Task Configuration': '扩展任务Config',
  'Task Priority': '任务优先级',
  External: '外部',
  Connector: 'Connector',
  'Must configure Connector': '必须Configure Connector',
  'Connector Id': 'Connector ID',
  Implementation: '实现方式',
  'Field Injections': '字段注入',
  Fields: '字段',
  'Result Variable': 'Result Variable',
  Topic: '主题',
  'Configure Connector': 'Configure Connector',
  'Input Parameter': 'Input Parameter',
  Assignee: '代理人',
  'Candidate Users': '候选用户',
  'Candidate Groups': '候选组',
  'Due Date': '到期Hour间',
  'Follow Up Date': 'Due Date',
  Priority: '优先级',
  'The follow up date as an EL expression (e.g. ${someDate} or an ISO date (e.g. 2015-06-26T09:54:00)':
    'Due date must be an EL expression like ${someDate}, or an ISO date like 2015-06-26T09:54:00',
  'The due date as an EL expression (e.g. ${someDate} or an ISO date (e.g. 2015-06-26T09:54:00)':
    'Due date must be an EL expression like ${someDate}, or an ISO date like 2015-06-26T09:54:00',
  Variables: '变量',
  'Candidate Starter Configuration': '候选人起动器Config',
  'Candidate Starter Groups': '候选人起动器组',
  'This maps to the process definition key.': 'This maps to the process definition key.',
  'Candidate Starter Users': '候选人起动器的用户',
  'Specify more than one user as a comma separated list.': 'Specified多个用户作为逗号Minute隔的列表。',
  'Tasklist Configuration': 'TasklistConfig',
  Startable: '启动',
  'Specify more than one group as a comma separated list.': 'Specified多个组作为逗号Minute隔的列表。'
}
